Create DevFest Modena 2025
cortinico/tech-conferences-italy pull request #117
Opened 2024-11-20 14:51 UTC by Davmuz

Addition of the DevFest Modena 2025 conference.

2024-11-20 15:19 UTC, danybony commented on _conferences/devfest-modena-2025.md
> +cfp_end:   2025-09-20
le date sono diverse da https://sessionize.com/devfest-modena-2025

2024-11-28 16:49 UTC, cortinico requested changes
see comment from [danybony](https://github.com/danybony)

2025-02-25 22:10 UTC, Davmuz commented
Perdonami ma non capisco, le date dell'evento sono le stesse: 4 e 5 ottobre 2025.

Le date per la call-for-papers che ho inserito nella commit sono quelle che probabilmente useremo, Sessionize in questo caso non è ancora aggiornato perché siamo lontani dall'inizio.

Se non ci sono altre cose vi chiedo per cortesia se possibile di pubblicare l'evento. Grazie.

2025-02-26 07:23 UTC, danybony commented
Per cortesia allora rimuovi le date della CFP se non sono quelle definitive, non andiamo ad inserire dati non corretti

2025-02-26 08:46 UTC, Davmuz commented
Rimosse (`patch-1`).

2025-02-26 08:50 UTC, danybony approved these changes

2025-02-26 08:50 UTC, merged