add some confs
cortinico/tech-conferences-italy pull request #5
Opened 2020-04-09 13:45 UTC by giuliatosato

2020-04-10 22:31 UTC, cortinico requested changes
Grazie mille. Ci sono due date da sistemare per caso o vanno bene cosi?

2020-04-10 22:31 UTC, cortinico commented on _conferences/sfday-2020.md
> +date_start: 2020-11-27
```suggestion
date_start: 2020-11-26
```

Il sito indica il 26 come workshop day?

2020-04-10 22:31 UTC, cortinico commented on _conferences/laravelday-2020.md
> +date_end:   2020-11-26
```suggestion
date_end:   2020-11-27
```
Vedi altro commento

2020-04-11 14:27 UTC, giuliatosato commented on _conferences/laravelday-2020.md
> +date_end:   2020-11-26
vanno bene così, preferisco indicare solo il giorno della conferenza. grazie!

2020-04-11 22:07 UTC, cortinico approved these changes

2020-04-11 22:07 UTC, merged